API_KEY ='777'
API_URL_ID = ${{ secrets.API_URL_ID }}
API_URL_INVOICES = ${{ secrets.API_URL_INVOICES }}
AUTH_URL = ${{ secrets.AUTH_URL }}
AUTH_CLIENT_ID = ${{ secrets.AUTH_CLIENT_ID }}
AUTH_CLIENT_SECRET = ${{ secrets.AUTH_CLIENT_SECRET }}
