API_KEY ='777'
API_URL_ID = 'https://enigaseluce-evd.eniplenitude.com/ocr-api/IdentityDocumentOCR/v1'
API_URL_INVOICES = 'https://enigaseluce-evd.eniplenitude.com/ocr-api/BillOCR/v1'
AUTH_URL ='https://enigaseluce-evd.eniplenitude.com/oauth/client_credential/accesstoken?grant_type=client_credentials'
AUTH_CLIENT_ID ='nlPVeFqJ3lXxxnclVWtgsI8l6ugAMLBxMOGAxH0BblLdAH3u'
AUTH_CLIENT_SECRET ='L76fykNISVC3TwAXFUjlH9FTuaEeBqZKnyAb3pAGw0TPoC1tl1siqWhQCqDYdRv1'
